--------------------------------------------------------
--  File created - Monday-March-28-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NEWROOM
--------------------------------------------------------

  CREATE TABLE "ORA1"."NEWROOM" 
   (	"ROOMNUM" NUMBER(*,0), 
	"DIRECTIONCHOICE" CHAR(1 BYTE), 
	"NEWROOMNUM" NUMBER(*,0), 
	"NEWROOMVISITED" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORA1.NEWROOM
SET DEFINE OFF;
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (0,'N',1,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (1,'N',2,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (2,'W',3,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (2,'S',1,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (2,'E',4,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (3,'N',5,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (3,'E',2,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (4,'W',2,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (4,'N',7,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (5,'S',3,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (6,'E',7,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (6,'S',8,'0');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (7,'W',6,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (7,'S',4,'1');
Insert into ORA1.NEWROOM (ROOMNUM,DIRECTIONCHOICE,NEWROOMNUM,NEWROOMVISITED) values (8,'W',6,'1');
--------------------------------------------------------
--  DDL for Index PK_NEWROOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."PK_NEWROOM" ON "ORA1"."NEWROOM" ("ROOMNUM", "DIRECTIONCHOICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NEWROOM
--------------------------------------------------------

  ALTER TABLE "ORA1"."NEWROOM" ADD CONSTRAINT "PK_NEWROOM" PRIMARY KEY ("ROOMNUM", "DIRECTIONCHOICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
